apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  # --- BFF Internal Routing URLs ---
  IDENTITY_SERVICE_URL: "http://techsalary-identity.app.svc.cluster.local:8001/api/v1"
  SEARCH_SERVICE_URL: "http://techsalary-search.app.svc.cluster.local:8004/api/v1"
  SALARY_SERVICE_URL: "http://techsalary-salary.app.svc.cluster.local:8003/api/v1/salary"
  STAT_SERVICE_URL: "http://techsalary-stats.app.svc.cluster.local:8006/api/v1"
  VOTE_SERVICE_URL: "http://techsalary-vote.app.svc.cluster.local:8005/vote"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  # Sensitive data (passwords, keys)
  DATABASE_URL: "postgresql://myuser:mypassword@techsalary-postgres.data.svc.cluster.local:5432/techsalary_db"
  SECRET_KEY: "super_secret_key_for_dev_only"