apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsalary-identity
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: techsalaryacrd4.azurecr.io/techsalary-identity:latest
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: techsalary-identity
  namespace: app
spec:
  selector:
    app: identity
  ports:
    - port: 8001
      targetPort: 8001