apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsalary-stats
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
        - name: stats
          image: techsalaryacrd4.azurecr.io/techsalary-stats:latest
          ports:
            - containerPort: 8006
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: techsalary-stats
  namespace: app
spec:
  selector:
    app: stats
  ports:
    - port: 8006
      targetPort: 8006