apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsalary-salary
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salary
  template:
    metadata:
      labels:
        app: salary
    spec:
      containers:
        - name: salary
          image: techsalaryacrd4.azurecr.io/techsalary-salary:latest
          ports:
            - containerPort: 8003
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: techsalary-salary
  namespace: app
spec:
  selector:
    app: salary
  ports:
    - port: 8003
      targetPort: 8003