version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: salary-postgres
    environment:
      POSTGRES_DB: salarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  stats-service:
    build: .
    container_name: stats-service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/salarydb
      APP_NAME: stats-service
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      CORS_ORIGINS: "*"
    ports:
      - "8000:8000"

volumes:
  postgres_data: