apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techsalary-ingress
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://40.119.238.174"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Accept,Origin"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "20.197.82.255.nip.io"
      secretName: techsalary-tls-secret
  rules:
    - host: "20.197.82.255.nip.io"
      http:
        paths:
          # 1. Allow all actual API traffic through to the BFF
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: techsalary-bff
                port:
                  number: 8000

          # 2. Allow the Swagger UI HTML page through to the BFF
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: techsalary-bff
                port:
                  number: 8000

          # 3. Allow the JSON schema that Swagger needs to render the page
          - path: /openapi.json
            pathType: ImplementationSpecific
            backend:
              service:
                name: techsalary-bff
                port:
                  number: 8000

          # 4. Allow BFF Health check
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: techsalary-bff
                port:
                  number: 8000